services:
  - type: web
    name: webpilot
    env: node
    plan: free
    rootDir: server
    buildCommand: |
      cd ../client
      npm install
      npm run build
      cd ../server
      npm install
    startCommand: node index.js
